### PR TITLE
SCRUM-43-ansible [FEAT] Ansible deployment, Terraform fixes & OCI implementation

### PR DESCRIPTION
**Pull request by Arthurdw**
Full documentation of this PR can be found in the representative README's

- [Ansible & Terraform](https://github.com/vibbits/irefindex/tree/SCRUM-43-ansible/vsc#readme)
- [OCI](https://github.com/vibbits/irefindex/tree/SCRUM-43-ansible/oci#readme)

### Ansible 

- [x] iRInit 
- [x] iRDownload
- [x] iRUnpack
- [x] iRManifest
- [x] iRParse
- [x] iRImport
- [x] iRBuild
- [x] Parallelized processing

### Terraform

- [x] Automatic SSH known hosts removal
- [x] Automatic invocation of the iRInit and iRDownload playbooks

### OCI

> Note: No deployment to a container registry has been done yet as this should be done by a VIB representative member

- [x] Built-time optimization of already executing the iRInit playbook
- [x] Docker container

### CODE REVIEW

**Review by MaybeJustJames — COMMENTED** [review]
Please remove the IDE dotfiles. And the `.assets` directory unless there's a compelling reason to keep it?

**Review by MaybeJustJames — CHANGES_REQUESTED** [review]
After the above minor cleanups I'm happy to merge this.

**Comment by Arthurdw** [comment]
> After the above minor cleanups I'm happy to merge this.

I agree on removing the editor files (will do when I'm back) but would prefer to keep the .assets folder as this contains all readme assets (like images etc) unless you have a suggestion to where to put these files.

**Comment by MaybeJustJames** [comment]
> I [...] would prefer to keep the .assets folder as this contains all readme assets (like images etc) unless you have a suggestion to where to put these files.

Ok. That's an excellent reason to keep them :) Then just delete the IDE folders and I'm happy to merge. If you're on holiday then I hope you enjoy it. No rush here

**Comment by Arthurdw** [comment]
> Ok. That's an excellent reason to keep them :) Then just delete the IDE folders and I'm happy to merge. If you're on holiday then I hope you enjoy it. No rush here

Alright, the `.idea` folder and `commitizen` config have been removed.

**Comment by Arthurdw** [comment]
> Lovely! Thank you for all of your hard work

It was a pleasure, I believe we should wait for @abotzki to review before merge right?

**Pull request merged**
